const express = require('express');
const router = express.Router();

const { signup, verifyEmail, login, makeInfo, getProfile, updateUserProfile, refreshStateUser, updateAvatarAndBackground } = require('../controllers/User');

const { Users, Posts } = require("../models");
const { validateToken } = require('../middlewares/AuthMiddleware');
const uploadMiddleware = require('../middlewares/multer');

// sign up
router.post("/", signup);

// make new user info
router.put("/", validateToken, makeInfo);

// login
router.post('/login', login);

//verify email
router.post("/verify", verifyEmail);

// update username
router.put("/name/:id", validateToken, async (req, res) => {
  try {
    const id = req.params.id;
    const user = await Users.findByPk(id);

    if (user.id != id) throw new Error("You dont have permission")
    const username = await user.update({ username: req.body.username });
    res.status.json(username);
  } catch (err) {
    res.status(400).json({
      message: "Update failed",
      error: err.message
    });
  }
});

// get user profile
router.get("/:info", validateToken, getProfile);

//update user profile
router.put("/changeinfo", validateToken, updateUserProfile);

// get owner profile by id
router.get("/user/refresh", validateToken, refreshStateUser);

// update avatar
router.put("/upload", validateToken, uploadMiddleware, updateAvatarAndBackground);

router.post("/bulkCreate", async (req, res) => {

  await Users.bulkCreate([
    {
      "username": "Meaghan",
      "password": "tjTpn7RDxPYzX_q",
      "email": "Kelsi61@yahoo.com",
      "nickname": "Recumbent",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "4",
      "isActive": "5",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#adaea3",
      "address": "blue",
      "story": "Wisoky",
      "workAt": "sewer",
      "studyAt": "azure",
      "favorites": "indigo",
      "birthday": "withdrawal",
      "createdAt": "2024-03-15T21:21:59.196Z",
      "updatedAt": "2024-03-16T02:43:47.362Z",
      "ids": "1"
    },
    {
      "username": "Ward",
      "password": "4W4jDCyuwxzM9rl",
      "email": "Delpha.Boehm77@yahoo.com",
      "nickname": "Account",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "9",
      "isActive": "1",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#d4de0d",
      "address": "ensure",
      "story": "Hop",
      "workAt": "usable",
      "studyAt": "embrace",
      "favorites": "Northwest",
      "birthday": "Fresh",
      "createdAt": "2024-03-15T21:21:39.956Z",
      "updatedAt": "2024-03-16T08:55:15.951Z",
      "ids": "2"
    },
    {
      "username": "Rosalia",
      "password": "jPPlQahpxEOd0nb",
      "email": "Patsy.Klocko98@gmail.com",
      "nickname": "connect",
      "gender": "female",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "8",
      "isActive": "4",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#432d4c",
      "address": "card",
      "story": "Lutetium",
      "workAt": "panel",
      "studyAt": "Steel",
      "favorites": "grey",
      "birthday": "Borders",
      "createdAt": "2024-03-16T03:39:43.006Z",
      "updatedAt": "2024-03-16T05:40:28.787Z",
      "ids": "3"
    },
    {
      "username": "Jaqueline",
      "password": "mdilnTP8FbRyeTd",
      "email": "Zakary37@yahoo.com",
      "nickname": "Rubidium",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "3",
      "isActive": "4",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#9ecd05",
      "address": "where",
      "story": "Fitness",
      "workAt": "Chevrolet",
      "studyAt": "driver",
      "favorites": "Northwest",
      "birthday": "male",
      "createdAt": "2024-03-16T03:10:46.516Z",
      "updatedAt": "2024-03-15T11:51:14.941Z",
      "ids": "4"
    },
    {
      "username": "Dalton",
      "password": "4QvzSLwoHXmn_IH",
      "email": "Jasen.Connelly72@gmail.com",
      "nickname": "generating",
      "gender": "female",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "1",
      "isActive": "2",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#ef73a5",
      "address": "swamp",
      "story": "Multigender",
      "workAt": "duh",
      "studyAt": "greedily",
      "favorites": "system",
      "birthday": "withdrawal",
      "createdAt": "2024-03-16T10:58:22.404Z",
      "updatedAt": "2024-03-16T07:00:28.117Z",
      "ids": "5"
    },
    {
      "username": "Grover",
      "password": "xTXj_fD2L3juz4k",
      "email": "Zoie.Morissette@hotmail.com",
      "nickname": "systemic",
      "gender": "female",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "1",
      "isActive": "1",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#e5a74d",
      "address": "Grocery",
      "story": "BMX",
      "workAt": "South",
      "studyAt": "Lead",
      "favorites": "female",
      "birthday": "migration",
      "createdAt": "2024-03-15T17:04:40.909Z",
      "updatedAt": "2024-03-16T06:23:07.734Z",
      "ids": "6"
    },
    {
      "username": "Alexandro",
      "password": "n6AjO6lYjR3eHnq",
      "email": "Kenyatta17@yahoo.com",
      "nickname": "reboot",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "4",
      "isActive": "4",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#db1a80",
      "address": "and",
      "story": "vel",
      "workAt": "turquoise",
      "studyAt": "black",
      "favorites": "topic",
      "birthday": "oh",
      "createdAt": "2024-03-16T00:40:05.647Z",
      "updatedAt": "2024-03-15T20:04:37.583Z",
      "ids": "7"
    },
    {
      "username": "Albin",
      "password": "wzYzD6Hx3cyyViW",
      "email": "Candice.Connelly@yahoo.com",
      "nickname": "Plastic",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "6",
      "isActive": "9",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#b833e5",
      "address": "maximize",
      "story": "Diesel",
      "workAt": "productize",
      "studyAt": "ick",
      "favorites": "digital",
      "birthday": "female",
      "createdAt": "2024-03-15T12:58:34.104Z",
      "updatedAt": "2024-03-15T13:56:47.722Z",
      "ids": "8"
    },
    {
      "username": "Jay",
      "password": "hs3QpdHr4q2fd_g",
      "email": "Ubaldo.Wolf1@gmail.com",
      "nickname": "South",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "8",
      "isActive": "2",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#fe3e30",
      "address": "likewise",
      "story": "Midland",
      "workAt": "transmitting",
      "studyAt": "South",
      "favorites": "West",
      "birthday": "Cambridgeshire",
      "createdAt": "2024-03-16T03:57:19.543Z",
      "updatedAt": "2024-03-16T02:00:40.038Z",
      "ids": "9"
    },
    {
      "username": "Marielle",
      "password": "WHMvSvaMgDie7v0",
      "email": "Antwon85@hotmail.com",
      "nickname": "matrix",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "8",
      "isActive": "7",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#b6efe3",
      "address": "Berkshire",
      "story": "Franey",
      "workAt": "Internal",
      "studyAt": "facere",
      "favorites": "voluptatem",
      "birthday": "quantify",
      "createdAt": "2024-03-15T21:13:28.231Z",
      "updatedAt": "2024-03-15T14:07:42.041Z",
      "ids": "10"
    },
    {
      "username": "Ursula",
      "password": "30GDZw7clJfaXOA",
      "email": "Jeramie.Paucek61@gmail.com",
      "nickname": "program",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "5",
      "isActive": "2",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#8054a7",
      "address": "West",
      "story": "male",
      "workAt": "crowded",
      "studyAt": "sky",
      "favorites": "methodologies",
      "birthday": "elongate",
      "createdAt": "2024-03-15T22:20:01.089Z",
      "updatedAt": "2024-03-16T03:11:07.864Z",
      "ids": "11"
    },
    {
      "username": "Gabriel",
      "password": "FGCNBViyv_eJwEr",
      "email": "Edd.Waelchi@hotmail.com",
      "nickname": "gold",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "2",
      "isActive": "9",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#cbcba1",
      "address": "virtual",
      "story": "Central",
      "workAt": "Gender",
      "studyAt": "Connecticut",
      "favorites": "Tricycle",
      "birthday": "IB",
      "createdAt": "2024-03-15T13:36:21.785Z",
      "updatedAt": "2024-03-15T14:32:17.234Z",
      "ids": "12"
    },
    {
      "username": "Charles",
      "password": "s0SWWEF_pY2TzfP",
      "email": "Jena.Stark@hotmail.com",
      "nickname": "Garden",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "2",
      "isActive": "1",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#ac69f7",
      "address": "minus",
      "story": "up",
      "workAt": "Temecula",
      "studyAt": "Organic",
      "favorites": "utterly",
      "birthday": "lime",
      "createdAt": "2024-03-15T21:25:23.757Z",
      "updatedAt": "2024-03-16T11:29:33.340Z",
      "ids": "13"
    },
    {
      "username": "Christy",
      "password": "wDkpl4YIZI04YMx",
      "email": "Alvah.Bauch@hotmail.com",
      "nickname": "Boulder",
      "gender": "female",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "2",
      "isActive": "6",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#6f0c43",
      "address": "ugh",
      "story": "Wooden",
      "workAt": "Beauty",
      "studyAt": "matrices",
      "favorites": "male",
      "birthday": "Dollar",
      "createdAt": "2024-03-16T08:57:02.958Z",
      "updatedAt": "2024-03-15T15:21:16.623Z",
      "ids": "14"
    },
    {
      "username": "Leonardo",
      "password": "daMeKJs6n7yUTnf",
      "email": "Sandy.Wuckert@yahoo.com",
      "nickname": "Tactics",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "5",
      "isActive": "4",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#3baebd",
      "address": "Industrial",
      "story": "before",
      "workAt": "Waelchi",
      "studyAt": "forecast",
      "favorites": "Harris",
      "birthday": "Soft",
      "createdAt": "2024-03-15T20:14:43.106Z",
      "updatedAt": "2024-03-15T14:00:44.658Z",
      "ids": "15"
    },
    {
      "username": "Dillan",
      "password": "rrcoFAWahicxv1H",
      "email": "Crystal_Padberg54@gmail.com",
      "nickname": "pascal",
      "gender": "female",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "2",
      "isActive": "6",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#1ba0ce",
      "address": "plum",
      "story": "programming",
      "workAt": "Facilitator",
      "studyAt": "Israel",
      "favorites": "Smart",
      "birthday": "protocol",
      "createdAt": "2024-03-15T16:30:52.407Z",
      "updatedAt": "2024-03-16T07:40:18.215Z",
      "ids": "16"
    },
    {
      "username": "Wilburn",
      "password": "USA_77aAsZb3GbK",
      "email": "Skye52@gmail.com",
      "nickname": "expire",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "1",
      "isActive": "3",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#bbeda4",
      "address": "recess",
      "story": "East",
      "workAt": "bah",
      "studyAt": "steradian",
      "favorites": "Specialist",
      "birthday": "carefully",
      "createdAt": "2024-03-15T12:05:43.695Z",
      "updatedAt": "2024-03-15T19:08:03.209Z",
      "ids": "17"
    },
    {
      "username": "Spencer",
      "password": "TXuXKL9avZChi3R",
      "email": "Kenyon12@yahoo.com",
      "nickname": "connect",
      "gender": "female",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "7",
      "isActive": "6",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#8e30ed",
      "address": "Accounts",
      "story": "Streamlined",
      "workAt": "fooey",
      "studyAt": "Cadillac",
      "favorites": "yet",
      "birthday": "crewmember",
      "createdAt": "2024-03-16T09:41:18.261Z",
      "updatedAt": "2024-03-16T08:36:21.577Z",
      "ids": "18"
    },
    {
      "username": "Matt",
      "password": "WUyItBcKaplFm5d",
      "email": "Cynthia.Rau94@hotmail.com",
      "nickname": "right",
      "gender": "female",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "8",
      "isActive": "5",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#3eecce",
      "address": "Global",
      "story": "Tricycle",
      "workAt": "Southeast",
      "studyAt": "Interactions",
      "favorites": "Bacon",
      "birthday": "overriding",
      "createdAt": "2024-03-16T02:59:00.546Z",
      "updatedAt": "2024-03-16T03:28:03.704Z",
      "ids": "19"
    },
    {
      "username": "Alba",
      "password": "M7VEVii6aTo3pgM",
      "email": "Ansel20@gmail.com",
      "nickname": "North",
      "gender": "female",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "5",
      "isActive": "8",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#5997e6",
      "address": "content",
      "story": "Passenger",
      "workAt": "patiently",
      "studyAt": "Club",
      "favorites": "that",
      "birthday": "Wooden",
      "createdAt": "2024-03-16T09:05:12.188Z",
      "updatedAt": "2024-03-16T07:32:35.647Z",
      "ids": "20"
    },
    {
      "username": "Sanford",
      "password": "tkqhGLIEdJy9mwP",
      "email": "Zakary.DuBuque@hotmail.com",
      "nickname": "teal",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "6",
      "isActive": "4",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#cb1890",
      "address": "syndicate",
      "story": "impolite",
      "workAt": "Market",
      "studyAt": "Loan",
      "favorites": "scrawny",
      "birthday": "Orchestrator",
      "createdAt": "2024-03-15T17:05:46.045Z",
      "updatedAt": "2024-03-15T13:52:24.795Z",
      "ids": "21"
    },
    {
      "username": "Citlalli",
      "password": "vZb3Cf654NG7s0p",
      "email": "Zachariah.Ryan@hotmail.com",
      "nickname": "VGA",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "4",
      "isActive": "7",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#5fc9ea",
      "address": "M2F",
      "story": "Markets",
      "workAt": "Computers",
      "studyAt": "Movies",
      "favorites": "drat",
      "birthday": "Woman",
      "createdAt": "2024-03-16T00:24:51.755Z",
      "updatedAt": "2024-03-15T20:27:57.506Z",
      "ids": "22"
    },
    {
      "username": "Colten",
      "password": "gUy5t5SVVgWwVDn",
      "email": "Alverta.Effertz45@gmail.com",
      "nickname": "Refined",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "5",
      "isActive": "4",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#2eeaa4",
      "address": "circa",
      "story": "Southeast",
      "workAt": "Delaware",
      "studyAt": "azure",
      "favorites": "Europium",
      "birthday": "majestically",
      "createdAt": "2024-03-15T15:45:55.554Z",
      "updatedAt": "2024-03-15T15:38:11.331Z",
      "ids": "23"
    },
    {
      "username": "Marta",
      "password": "pISmGUFZGcl9qlc",
      "email": "Nick.Tromp88@hotmail.com",
      "nickname": "especially",
      "gender": "female",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "2",
      "isActive": "7",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#489b92",
      "address": "channels",
      "story": "drat",
      "workAt": "payment",
      "studyAt": "size",
      "favorites": "for",
      "birthday": "FTP",
      "createdAt": "2024-03-15T17:06:56.352Z",
      "updatedAt": "2024-03-16T03:48:16.795Z",
      "ids": "24"
    },
    {
      "username": "Lynn",
      "password": "lqbBYG9p9Jypu_r",
      "email": "Herman_Schuppe@hotmail.com",
      "nickname": "Southeast",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "8",
      "isActive": "8",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#af2b71",
      "address": "forget",
      "story": "parse",
      "workAt": "East",
      "studyAt": "platforms",
      "favorites": "aggregate",
      "birthday": "Games",
      "createdAt": "2024-03-16T05:51:11.689Z",
      "updatedAt": "2024-03-16T10:57:30.738Z",
      "ids": "25"
    },
    {
      "username": "Adrianna",
      "password": "_vTQyJj3TQHT2Kb",
      "email": "Agnes6@yahoo.com",
      "nickname": "Integration",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "4",
      "isActive": "8",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#ff0a1f",
      "address": "Convertible",
      "story": "lavender",
      "workAt": "Credit",
      "studyAt": "deliver",
      "favorites": "in",
      "birthday": "microchip",
      "createdAt": "2024-03-16T01:29:37.350Z",
      "updatedAt": "2024-03-16T06:47:33.730Z",
      "ids": "26"
    },
    {
      "username": "Devyn",
      "password": "6INzpK9791yqjzQ",
      "email": "Diamond27@gmail.com",
      "nickname": "Kenya",
      "gender": "female",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "3",
      "isActive": "9",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#0d70da",
      "address": "Berkshire",
      "story": "Palau",
      "workAt": "Sharable",
      "studyAt": "ancestor",
      "favorites": "Somalia",
      "birthday": "Movies",
      "createdAt": "2024-03-16T10:14:38.414Z",
      "updatedAt": "2024-03-16T11:31:42.082Z",
      "ids": "27"
    },
    {
      "username": "Reinhold",
      "password": "SLGJWLl8Utys81M",
      "email": "Darrion.Bruen@gmail.com",
      "nickname": "breakdown",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "8",
      "isActive": "6",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#f21b17",
      "address": "Cloned",
      "story": "Vermont",
      "workAt": "Iowa",
      "studyAt": "primary",
      "favorites": "up",
      "birthday": "Northwest",
      "createdAt": "2024-03-16T08:46:29.221Z",
      "updatedAt": "2024-03-15T17:55:33.685Z",
      "ids": "28"
    },
    {
      "username": "Gwen",
      "password": "UjLIZfeguZbOzyt",
      "email": "Elvera_Graham58@hotmail.com",
      "nickname": "male",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "1",
      "isActive": "5",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#ddbdfc",
      "address": "North",
      "story": "Global",
      "workAt": "Rap",
      "studyAt": "snuff",
      "favorites": "Tuna",
      "birthday": "circuit",
      "createdAt": "2024-03-15T21:23:17.932Z",
      "updatedAt": "2024-03-15T12:36:14.843Z",
      "ids": "29"
    },
    {
      "username": "Gus",
      "password": "P05SdUkmzyEmiNi",
      "email": "Kayla.Botsford93@yahoo.com",
      "nickname": "Salad",
      "gender": "female",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "8",
      "isActive": "7",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#1f3cc6",
      "address": "fill",
      "story": "olive",
      "workAt": "scared",
      "studyAt": "North",
      "favorites": "blanditiis",
      "birthday": "reproachfully",
      "createdAt": "2024-03-16T02:33:16.709Z",
      "updatedAt": "2024-03-15T17:17:52.669Z",
      "ids": "30"
    },
    {
      "username": "Erika",
      "password": "j_cWIAtPdx35bAZ",
      "email": "Ricky10@yahoo.com",
      "nickname": "similique",
      "gender": "female",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "2",
      "isActive": "5",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#a29cd4",
      "address": "impactful",
      "story": "white",
      "workAt": "highly",
      "studyAt": "Senior",
      "favorites": "Amina",
      "birthday": "Shoes",
      "createdAt": "2024-03-15T20:40:36.641Z",
      "updatedAt": "2024-03-15T15:22:03.630Z",
      "ids": "31"
    },
    {
      "username": "Delta",
      "password": "qn9e9aaTkouBJAY",
      "email": "Torey_Parisian@yahoo.com",
      "nickname": "at",
      "gender": "female",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "3",
      "isActive": "4",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#a13ec0",
      "address": "payment",
      "story": "female",
      "workAt": "Clothing",
      "studyAt": "quote",
      "favorites": "Checking",
      "birthday": "Littleton",
      "createdAt": "2024-03-16T00:25:54.683Z",
      "updatedAt": "2024-03-16T07:09:37.043Z",
      "ids": "32"
    },
    {
      "username": "Mona",
      "password": "JvZu8aeUPQl9r9F",
      "email": "Jude67@hotmail.com",
      "nickname": "Carbon",
      "gender": "female",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "7",
      "isActive": "5",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#1e0c21",
      "address": "tesla",
      "story": "Rock",
      "workAt": "Tugrik",
      "studyAt": "Savings",
      "favorites": "East",
      "birthday": "transmit",
      "createdAt": "2024-03-15T12:08:33.085Z",
      "updatedAt": "2024-03-16T11:31:10.601Z",
      "ids": "33"
    },
    {
      "username": "Delaney",
      "password": "M937NQJptlVjf_1",
      "email": "Katlynn.Mosciski@yahoo.com",
      "nickname": "redundant",
      "gender": "female",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "5",
      "isActive": "6",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#0ed8da",
      "address": "Extensions",
      "story": "Hatchback",
      "workAt": "District",
      "studyAt": "lime",
      "favorites": "Cotton",
      "birthday": "generously",
      "createdAt": "2024-03-16T03:46:37.413Z",
      "updatedAt": "2024-03-15T17:35:13.818Z",
      "ids": "34"
    },
    {
      "username": "Vincenza",
      "password": "wBeWeqOA2N0KPNV",
      "email": "Marcella.Hudson28@yahoo.com",
      "nickname": "teal",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "4",
      "isActive": "3",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#d5ed8e",
      "address": "payment",
      "story": "ivory",
      "workAt": "separately",
      "studyAt": "Blanche",
      "favorites": "withdrawal",
      "birthday": "Southwest",
      "createdAt": "2024-03-15T12:41:52.689Z",
      "updatedAt": "2024-03-15T17:06:26.933Z",
      "ids": "35"
    },
    {
      "username": "Devyn",
      "password": "2EAM3_vhp1Nbaqx",
      "email": "Theodora_Mitchell@yahoo.com",
      "nickname": "Transmasculine",
      "gender": "female",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "4",
      "isActive": "1",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#b11ff1",
      "address": "Elkhart",
      "story": "Coordinator",
      "workAt": "Operations",
      "studyAt": "Convertible",
      "favorites": "hook",
      "birthday": "Soft",
      "createdAt": "2024-03-16T03:10:49.578Z",
      "updatedAt": "2024-03-15T11:53:52.375Z",
      "ids": "36"
    },
    {
      "username": "Carol",
      "password": "O0E7JwjJQCvAGdP",
      "email": "Aimee.Dach@gmail.com",
      "nickname": "violet",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "7",
      "isActive": "4",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#c1cdad",
      "address": "christen",
      "story": "snarling",
      "workAt": "Card",
      "studyAt": "magenta",
      "favorites": "West",
      "birthday": "what",
      "createdAt": "2024-03-16T08:26:57.662Z",
      "updatedAt": "2024-03-16T06:42:22.322Z",
      "ids": "37"
    },
    {
      "username": "Randi",
      "password": "y1Y2FhcdeydrQE7",
      "email": "Bernadine_Barton@yahoo.com",
      "nickname": "Bedfordshire",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "6",
      "isActive": "8",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#fee6eb",
      "address": "transmitter",
      "story": "Functionality",
      "workAt": "Southwest",
      "studyAt": "coherent",
      "favorites": "Avon",
      "birthday": "Frozen",
      "createdAt": "2024-03-16T04:25:08.806Z",
      "updatedAt": "2024-03-16T03:58:47.847Z",
      "ids": "38"
    },
    {
      "username": "Monroe",
      "password": "s19KriWCmjUKpbW",
      "email": "Gertrude51@yahoo.com",
      "nickname": "Praseodymium",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "2",
      "isActive": "1",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#b4ed43",
      "address": "orchid",
      "story": "API",
      "workAt": "aw",
      "studyAt": "blue",
      "favorites": "athwart",
      "birthday": "Honda",
      "createdAt": "2024-03-15T15:59:34.483Z",
      "updatedAt": "2024-03-15T19:43:51.792Z",
      "ids": "39"
    },
    {
      "username": "Oswald",
      "password": "xFNtL9IWRrc7ewD",
      "email": "Colby_Tillman@gmail.com",
      "nickname": "mobile",
      "gender": "female",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "8",
      "isActive": "1",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#10c929",
      "address": "Car",
      "story": "primary",
      "workAt": "Brand",
      "studyAt": "Smart",
      "favorites": "watt",
      "birthday": "um",
      "createdAt": "2024-03-15T15:54:47.903Z",
      "updatedAt": "2024-03-16T03:14:11.676Z",
      "ids": "40"
    },
    {
      "username": "Tremayne",
      "password": "XN_1Etnz5rrnUIq",
      "email": "Meghan.Hessel@yahoo.com",
      "nickname": "virtual",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "9",
      "isActive": "3",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#1bfded",
      "address": "Car",
      "story": "Hong",
      "workAt": "Fresh",
      "studyAt": "Producer",
      "favorites": "bus",
      "birthday": "bifurcated",
      "createdAt": "2024-03-16T10:35:49.153Z",
      "updatedAt": "2024-03-16T03:58:22.560Z",
      "ids": "41"
    },
    {
      "username": "Christophe",
      "password": "bZfdp5mColsUzAP",
      "email": "Reece_Russel56@gmail.com",
      "nickname": "Car",
      "gender": "female",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "6",
      "isActive": "1",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#02ff3f",
      "address": "Metal",
      "story": "Dynamic",
      "workAt": "ack",
      "studyAt": "vivaciously",
      "favorites": "Rock",
      "birthday": "vertical",
      "createdAt": "2024-03-16T09:34:41.725Z",
      "updatedAt": "2024-03-16T05:23:49.572Z",
      "ids": "42"
    },
    {
      "username": "Johnpaul",
      "password": "5eNWGmLsN6_EOys",
      "email": "Elouise_Muller99@gmail.com",
      "nickname": "sensor",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "9",
      "isActive": "1",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#2418bb",
      "address": "neural",
      "story": "tea",
      "workAt": "Interactions",
      "studyAt": "deposit",
      "favorites": "Configuration",
      "birthday": "Lock",
      "createdAt": "2024-03-15T17:59:49.430Z",
      "updatedAt": "2024-03-16T02:41:22.227Z",
      "ids": "43"
    },
    {
      "username": "Deion",
      "password": "iT1PpH99PYcpgr4",
      "email": "Sandy.Cartwright@yahoo.com",
      "nickname": "transition",
      "gender": "female",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "4",
      "isActive": "1",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#a4eaaa",
      "address": "moderator",
      "story": "World",
      "workAt": "Computers",
      "studyAt": "pink",
      "favorites": "Missouri",
      "birthday": "Gasoline",
      "createdAt": "2024-03-16T08:58:10.155Z",
      "updatedAt": "2024-03-15T22:30:11.032Z",
      "ids": "44"
    },
    {
      "username": "Jaquan",
      "password": "GBLQOBqdL4x6RKj",
      "email": "Antonette_Hamill57@gmail.com",
      "nickname": "matrix",
      "gender": "female",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "7",
      "isActive": "3",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#8cc861",
      "address": "Customizable",
      "story": "tarnish",
      "workAt": "HDD",
      "studyAt": "North",
      "favorites": "very",
      "birthday": "infrastructures",
      "createdAt": "2024-03-15T22:41:18.160Z",
      "updatedAt": "2024-03-15T17:16:35.531Z",
      "ids": "45"
    },
    {
      "username": "Rosalia",
      "password": "bE0Rdfvx_7vP5va",
      "email": "Floy.Lubowitz@hotmail.com",
      "nickname": "Bicycle",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "3",
      "isActive": "5",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#c4abd5",
      "address": "Frozen",
      "story": "ew",
      "workAt": "Bronze",
      "studyAt": "Hafnium",
      "favorites": "Ergonomic",
      "birthday": "Electronics",
      "createdAt": "2024-03-15T23:09:39.055Z",
      "updatedAt": "2024-03-16T11:04:22.620Z",
      "ids": "46"
    },
    {
      "username": "Chad",
      "password": "eugRjVRbekwR4MF",
      "email": "Deshaun70@yahoo.com",
      "nickname": "Cadmium",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "4",
      "isActive": "3",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#facafc",
      "address": "kookily",
      "story": "synthesize",
      "workAt": "SAS",
      "studyAt": "loud",
      "favorites": "Administrator",
      "birthday": "a",
      "createdAt": "2024-03-16T01:17:52.941Z",
      "updatedAt": "2024-03-15T17:47:44.841Z",
      "ids": "47"
    },
    {
      "username": "Mario",
      "password": "cejx9nYLfIhICZd",
      "email": "Larue.Zboncak@yahoo.com",
      "nickname": "aw",
      "gender": "female",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "3",
      "isActive": "4",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#24e6d1",
      "address": "Maximillia",
      "story": "Guam",
      "workAt": "Reggae",
      "studyAt": "withdrawal",
      "favorites": "between",
      "birthday": "Fitness",
      "createdAt": "2024-03-16T02:36:02.848Z",
      "updatedAt": "2024-03-16T07:19:45.276Z",
      "ids": "48"
    },
    {
      "username": "Millie",
      "password": "UKZsnr4T95yaV9r",
      "email": "Phoebe.Stiedemann20@hotmail.com",
      "nickname": "Mountain",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "9",
      "isActive": "6",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#ed3b2b",
      "address": "transmitter",
      "story": "deposit",
      "workAt": "Rock",
      "studyAt": "Bicycle",
      "favorites": "Cargo",
      "birthday": "near",
      "createdAt": "2024-03-16T08:25:33.961Z",
      "updatedAt": "2024-03-15T16:14:12.235Z",
      "ids": "49"
    },
    {
      "username": "Amina",
      "password": "MA6I6cQfGGSc1Jz",
      "email": "Green.Thompson@yahoo.com",
      "nickname": "Daija",
      "gender": "female",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "7",
      "isActive": "1",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#8fd8ba",
      "address": "Interface",
      "story": "FTP",
      "workAt": "Cargo",
      "studyAt": "Diesel",
      "favorites": "kilogram",
      "birthday": "Loan",
      "createdAt": "2024-03-15T22:00:25.909Z",
      "updatedAt": "2024-03-16T09:10:49.009Z",
      "ids": "50"
    },
    {
      "username": "Gladys",
      "password": "i44xtAKLEzCldTa",
      "email": "Lamont_Abbott@gmail.com",
      "nickname": "connecting",
      "gender": "female",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "3",
      "isActive": "4",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#0ef6e5",
      "address": "Account",
      "story": "Officer",
      "workAt": "matrix",
      "studyAt": "Automotive",
      "favorites": "um",
      "birthday": "East",
      "createdAt": "2024-03-15T17:34:30.530Z",
      "updatedAt": "2024-03-15T18:47:20.390Z",
      "ids": "51"
    },
    {
      "username": "Christop",
      "password": "VNTes3IPuWMYzXa",
      "email": "Quinten.Ruecker46@yahoo.com",
      "nickname": "lumen",
      "gender": "female",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "3",
      "isActive": "2",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#db8b1b",
      "address": "enhance",
      "story": "orientate",
      "workAt": "Planner",
      "studyAt": "5th",
      "favorites": "exuding",
      "birthday": "grizzled",
      "createdAt": "2024-03-16T04:35:38.182Z",
      "updatedAt": "2024-03-16T08:14:07.741Z",
      "ids": "52"
    },
    {
      "username": "Ali",
      "password": "0Ll7zb2zsrSqmmJ",
      "email": "Odessa_Roberts@yahoo.com",
      "nickname": "Legacy",
      "gender": "female",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "4",
      "isActive": "3",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#f94e2d",
      "address": "RSS",
      "story": "leading",
      "workAt": "Swiss",
      "studyAt": "colorfully",
      "favorites": "pillbox",
      "birthday": "Blues",
      "createdAt": "2024-03-16T08:55:12.200Z",
      "updatedAt": "2024-03-15T15:41:08.450Z",
      "ids": "53"
    },
    {
      "username": "Crystel",
      "password": "Du6WBuRXfCdwvLV",
      "email": "Keshaun_Lowe@gmail.com",
      "nickname": "Agent",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "9",
      "isActive": "8",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#edd6e2",
      "address": "Rial",
      "story": "vortals",
      "workAt": "Southeast",
      "studyAt": "irritate",
      "favorites": "Global",
      "birthday": "Convertible",
      "createdAt": "2024-03-16T11:08:15.554Z",
      "updatedAt": "2024-03-15T18:03:19.480Z",
      "ids": "54"
    },
    {
      "username": "Glennie",
      "password": "bnqWLpfGjs0REsx",
      "email": "Krystel.Nikolaus@hotmail.com",
      "nickname": "red",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "5",
      "isActive": "7",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#0f1309",
      "address": "Israel",
      "story": "once",
      "workAt": "deposit",
      "studyAt": "Plastic",
      "favorites": "Mouse",
      "birthday": "deposit",
      "createdAt": "2024-03-15T12:32:44.751Z",
      "updatedAt": "2024-03-15T18:26:01.029Z",
      "ids": "55"
    },
    {
      "username": "Lionel",
      "password": "B4Cyp7HbkXG7K_K",
      "email": "Chase_Powlowski2@yahoo.com",
      "nickname": "North",
      "gender": "female",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "8",
      "isActive": "2",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#f56abf",
      "address": "what",
      "story": "Brookline",
      "workAt": "Metal",
      "studyAt": "Hyundai",
      "favorites": "Home",
      "birthday": "silver",
      "createdAt": "2024-03-15T12:03:36.252Z",
      "updatedAt": "2024-03-15T20:08:36.053Z",
      "ids": "56"
    },
    {
      "username": "Larue",
      "password": "CYzG6vEOhCRGDTn",
      "email": "Jay.Yundt@yahoo.com",
      "nickname": "homogeneous",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "1",
      "isActive": "6",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#6399d7",
      "address": "Books",
      "story": "DNS",
      "workAt": "Specialist",
      "studyAt": "openly",
      "favorites": "Touring",
      "birthday": "Northwest",
      "createdAt": "2024-03-15T17:44:22.427Z",
      "updatedAt": "2024-03-15T22:53:46.803Z",
      "ids": "57"
    },
    {
      "username": "Nia",
      "password": "qnnBg3a27aT3bNZ",
      "email": "Ryder_Bartoletti@hotmail.com",
      "nickname": "Hybrid",
      "gender": "female",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "4",
      "isActive": "7",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#dabc6f",
      "address": "channels",
      "story": "zero",
      "workAt": "Bicycle",
      "studyAt": "Aston",
      "favorites": "vertical",
      "birthday": "payment",
      "createdAt": "2024-03-16T01:27:08.895Z",
      "updatedAt": "2024-03-15T23:55:31.883Z",
      "ids": "58"
    },
    {
      "username": "Axel",
      "password": "YVgyA1jv3Fs04sd",
      "email": "Gilberto_Langworth27@hotmail.com",
      "nickname": "Intelligent",
      "gender": "female",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "7",
      "isActive": "7",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#176c4d",
      "address": "hard",
      "story": "Sterling",
      "workAt": "gadzooks",
      "studyAt": "Executive",
      "favorites": "program",
      "birthday": "Fresh",
      "createdAt": "2024-03-16T10:21:40.218Z",
      "updatedAt": "2024-03-15T19:53:37.192Z",
      "ids": "59"
    },
    {
      "username": "Jadon",
      "password": "q358m1TMMKT6xUU",
      "email": "Uriel_Jacobson91@gmail.com",
      "nickname": "Rubber",
      "gender": "female",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "9",
      "isActive": "1",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#4d9d7b",
      "address": "Savings",
      "story": "farad",
      "workAt": "Books",
      "studyAt": "Loan",
      "favorites": "Future",
      "birthday": "unto",
      "createdAt": "2024-03-16T07:44:51.719Z",
      "updatedAt": "2024-03-15T22:03:14.940Z",
      "ids": "60"
    },
    {
      "username": "George",
      "password": "GbS6DPv7LpWSaAD",
      "email": "Constance0@hotmail.com",
      "nickname": "reinstate",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "1",
      "isActive": "6",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#3cf1a4",
      "address": "West",
      "story": "Regional",
      "workAt": "Representative",
      "studyAt": "payment",
      "favorites": "quantifying",
      "birthday": "generation",
      "createdAt": "2024-03-16T04:06:47.404Z",
      "updatedAt": "2024-03-16T08:53:31.705Z",
      "ids": "61"
    },
    {
      "username": "Ian",
      "password": "Og7hDysNZGU7oNB",
      "email": "Junius_Wunsch@hotmail.com",
      "nickname": "Cadillac",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "2",
      "isActive": "8",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#389657",
      "address": "Electric",
      "story": "Bacon",
      "workAt": "North",
      "studyAt": "how",
      "favorites": "Gloves",
      "birthday": "payment",
      "createdAt": "2024-03-15T12:50:44.926Z",
      "updatedAt": "2024-03-16T07:33:53.253Z",
      "ids": "62"
    },
    {
      "username": "Chandler",
      "password": "Hi512h87lyXl_Du",
      "email": "Frieda94@hotmail.com",
      "nickname": "transmitter",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "8",
      "isActive": "2",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#e9bb3a",
      "address": "hm",
      "story": "Towels",
      "workAt": "HTTP",
      "studyAt": "Automated",
      "favorites": "bitterly",
      "birthday": "whether",
      "createdAt": "2024-03-16T02:20:00.710Z",
      "updatedAt": "2024-03-16T04:40:18.125Z",
      "ids": "63"
    },
    {
      "username": "Yasmine",
      "password": "97Jh8uuFYLLhAxq",
      "email": "Darrion_Jacobi@hotmail.com",
      "nickname": "Lawrence",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "8",
      "isActive": "9",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#b5472e",
      "address": "Malagasy",
      "story": "Einsteinium",
      "workAt": "Northwest",
      "studyAt": "bypassing",
      "favorites": "against",
      "birthday": "Pants",
      "createdAt": "2024-03-16T09:32:07.791Z",
      "updatedAt": "2024-03-16T07:58:01.681Z",
      "ids": "64"
    },
    {
      "username": "Jacklyn",
      "password": "I_DInVXxhX7h5Cj",
      "email": "Crawford69@hotmail.com",
      "nickname": "pink",
      "gender": "female",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "3",
      "isActive": "1",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#ae76a6",
      "address": "Architect",
      "story": "Buckinghamshire",
      "workAt": "Northwest",
      "studyAt": "Swaziland",
      "favorites": "program",
      "birthday": "Lead",
      "createdAt": "2024-03-16T01:15:12.341Z",
      "updatedAt": "2024-03-15T22:00:27.410Z",
      "ids": "65"
    },
    {
      "username": "Monty",
      "password": "WjS_81M_5zlz5XP",
      "email": "Torrey35@yahoo.com",
      "nickname": "hacking",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "3",
      "isActive": "5",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#e5a9d6",
      "address": "Federation",
      "story": "female",
      "workAt": "unleash",
      "studyAt": "Trans",
      "favorites": "Rover",
      "birthday": "Hybrid",
      "createdAt": "2024-03-16T06:56:45.490Z",
      "updatedAt": "2024-03-16T03:05:35.751Z",
      "ids": "66"
    },
    {
      "username": "Landen",
      "password": "7_pzKRths39p9Ni",
      "email": "Shaylee.Gleichner51@yahoo.com",
      "nickname": "Virginia",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "8",
      "isActive": "2",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#8bb5aa",
      "address": "North",
      "story": "withdrawal",
      "workAt": "maroon",
      "studyAt": "don",
      "favorites": "contingency",
      "birthday": "array",
      "createdAt": "2024-03-15T20:09:31.188Z",
      "updatedAt": "2024-03-15T21:56:28.285Z",
      "ids": "67"
    },
    {
      "username": "Kaitlin",
      "password": "nWarjpMGIQoxWSg",
      "email": "Randy73@gmail.com",
      "nickname": "Manager",
      "gender": "female",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "6",
      "isActive": "4",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#593d73",
      "address": "XSS",
      "story": "Porsche",
      "workAt": "very",
      "studyAt": "Silver",
      "favorites": "unleash",
      "birthday": "Toys",
      "createdAt": "2024-03-15T18:26:09.550Z",
      "updatedAt": "2024-03-15T19:14:11.616Z",
      "ids": "68"
    },
    {
      "username": "Minnie",
      "password": "m_RpRVh4aT4EBFU",
      "email": "Sherwood.Rath@hotmail.com",
      "nickname": "compassionate",
      "gender": "female",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "7",
      "isActive": "2",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#f539e4",
      "address": "backing",
      "story": "Bike",
      "workAt": "Neon",
      "studyAt": "Isle",
      "favorites": "Tools",
      "birthday": "azure",
      "createdAt": "2024-03-15T21:31:33.521Z",
      "updatedAt": "2024-03-15T21:57:47.247Z",
      "ids": "69"
    },
    {
      "username": "Raphael",
      "password": "jKPdbw7eCz1Ic1p",
      "email": "Wilfred47@hotmail.com",
      "nickname": "Gasoline",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "4",
      "isActive": "8",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#c26c3b",
      "address": "Aruban",
      "story": "stealthily",
      "workAt": "amid",
      "studyAt": "North",
      "favorites": "furthermore",
      "birthday": "between",
      "createdAt": "2024-03-16T02:54:23.456Z",
      "updatedAt": "2024-03-15T18:20:45.914Z",
      "ids": "70"
    },
    {
      "username": "Korbin",
      "password": "1wvvxYZltkB8XQ8",
      "email": "Maryam81@yahoo.com",
      "nickname": "calculating",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "2",
      "isActive": "3",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#e47a6b",
      "address": "Franc",
      "story": "parody",
      "workAt": "hack",
      "studyAt": "West",
      "favorites": "whoever",
      "birthday": "copying",
      "createdAt": "2024-03-15T14:10:11.112Z",
      "updatedAt": "2024-03-15T11:41:26.147Z",
      "ids": "71"
    },
    {
      "username": "Jaylin",
      "password": "2pMBBYhCfl3WgBJ",
      "email": "Kaitlyn_Hamill40@yahoo.com",
      "nickname": "Marketing",
      "gender": "female",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "2",
      "isActive": "2",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#407bcd",
      "address": "Optimized",
      "story": "East",
      "workAt": "male",
      "studyAt": "pink",
      "favorites": "bluetooth",
      "birthday": "gold",
      "createdAt": "2024-03-16T07:03:51.407Z",
      "updatedAt": "2024-03-15T19:06:22.552Z",
      "ids": "72"
    },
    {
      "username": "Dakota",
      "password": "RUvYT_Hy8FSHGsK",
      "email": "Marisa.Sporer0@yahoo.com",
      "nickname": "Delray",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "8",
      "isActive": "2",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#ef5196",
      "address": "Utah",
      "story": "application",
      "workAt": "oh",
      "studyAt": "alarm",
      "favorites": "South",
      "birthday": "Diesel",
      "createdAt": "2024-03-15T16:51:54.093Z",
      "updatedAt": "2024-03-15T14:19:54.596Z",
      "ids": "73"
    },
    {
      "username": "Holden",
      "password": "15gvFwhOWp3lN9S",
      "email": "Alessandra.Klein14@yahoo.com",
      "nickname": "alliance",
      "gender": "female",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "5",
      "isActive": "1",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#ef4872",
      "address": "male",
      "story": "eek",
      "workAt": "deliverables",
      "studyAt": "truthfully",
      "favorites": "Interactions",
      "birthday": "Electronics",
      "createdAt": "2024-03-16T05:44:35.451Z",
      "updatedAt": "2024-03-16T01:17:40.749Z",
      "ids": "74"
    },
    {
      "username": "Ciara",
      "password": "ZN_N4Zoq4M0K0SR",
      "email": "Rosalee_Lind@yahoo.com",
      "nickname": "wherever",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "8",
      "isActive": "3",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#afac36",
      "address": "Sausages",
      "story": "Liaison",
      "workAt": "IB",
      "studyAt": "next",
      "favorites": "solid",
      "birthday": "Applications",
      "createdAt": "2024-03-15T18:55:51.041Z",
      "updatedAt": "2024-03-15T20:35:05.242Z",
      "ids": "75"
    },
    {
      "username": "Jakob",
      "password": "b5BafVxQv5XlZkY",
      "email": "Jordyn8@gmail.com",
      "nickname": "Michigan",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "5",
      "isActive": "9",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#aaf7fa",
      "address": "Kunde",
      "story": "Electric",
      "workAt": "state",
      "studyAt": "Market",
      "favorites": "weed",
      "birthday": "state",
      "createdAt": "2024-03-16T05:11:41.845Z",
      "updatedAt": "2024-03-15T17:29:44.233Z",
      "ids": "76"
    },
    {
      "username": "Ethyl",
      "password": "AYiN5r6kBUfI4jN",
      "email": "Sibyl_Conroy@hotmail.com",
      "nickname": "firewall",
      "gender": "female",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "9",
      "isActive": "4",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#3d4db1",
      "address": "Toys",
      "story": "repurpose",
      "workAt": "bandwidth",
      "studyAt": "mango",
      "favorites": "male",
      "birthday": "Refined",
      "createdAt": "2024-03-16T02:57:37.572Z",
      "updatedAt": "2024-03-15T23:02:27.150Z",
      "ids": "77"
    },
    {
      "username": "Daryl",
      "password": "0KWrJGpl5NiqEr8",
      "email": "Brody.VonRueden@hotmail.com",
      "nickname": "Minivan",
      "gender": "female",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "4",
      "isActive": "2",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#9aaccd",
      "address": "parsing",
      "story": "Sedan",
      "workAt": "Intersex",
      "studyAt": "synthesize",
      "favorites": "Gasoline",
      "birthday": "Data",
      "createdAt": "2024-03-15T15:02:10.831Z",
      "updatedAt": "2024-03-16T05:23:17.092Z",
      "ids": "78"
    },
    {
      "username": "Queenie",
      "password": "xaeAeMfMhbuok2N",
      "email": "Andreanne.VonRueden@hotmail.com",
      "nickname": "Identity",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "5",
      "isActive": "2",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#4aa2ef",
      "address": "alarm",
      "story": "Volkswagen",
      "workAt": "always",
      "studyAt": "Pop",
      "favorites": "Minnesota",
      "birthday": "Garden",
      "createdAt": "2024-03-16T10:47:25.659Z",
      "updatedAt": "2024-03-15T11:37:05.316Z",
      "ids": "79"
    },
    {
      "username": "Harry",
      "password": "kSD7atgdgno4nim",
      "email": "Kailee20@hotmail.com",
      "nickname": "Beauty",
      "gender": "female",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "6",
      "isActive": "8",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#95cef8",
      "address": "Investor",
      "story": "ebb",
      "workAt": "Leu",
      "studyAt": "feed",
      "favorites": "Officer",
      "birthday": "loyalty",
      "createdAt": "2024-03-16T02:56:04.919Z",
      "updatedAt": "2024-03-15T12:39:47.096Z",
      "ids": "80"
    },
    {
      "username": "Kylee",
      "password": "AA8VxI1aFYEsZ47",
      "email": "Rowland.Towne@yahoo.com",
      "nickname": "Miami",
      "gender": "female",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "6",
      "isActive": "5",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#3c9dd1",
      "address": "female",
      "story": "Norway",
      "workAt": "Towels",
      "studyAt": "tauten",
      "favorites": "commodi",
      "birthday": "channels",
      "createdAt": "2024-03-16T07:49:11.575Z",
      "updatedAt": "2024-03-15T19:28:25.869Z",
      "ids": "81"
    },
    {
      "username": "Isom",
      "password": "lbK3v8BSvHPb4o1",
      "email": "Jay25@hotmail.com",
      "nickname": "Mobility",
      "gender": "female",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "9",
      "isActive": "4",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#6ee19a",
      "address": "Gasoline",
      "story": "Sharable",
      "workAt": "Wisconsin",
      "studyAt": "Accountability",
      "favorites": "calculating",
      "birthday": "Investment",
      "createdAt": "2024-03-16T05:45:28.322Z",
      "updatedAt": "2024-03-15T17:25:24.277Z",
      "ids": "82"
    },
    {
      "username": "Sabryna",
      "password": "mzSUzBvNYAXtVqA",
      "email": "Maia.Ruecker@yahoo.com",
      "nickname": "software",
      "gender": "female",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "5",
      "isActive": "2",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#4e7c6e",
      "address": "quantify",
      "story": "digital",
      "workAt": "Northwest",
      "studyAt": "abandoned",
      "favorites": "innocent",
      "birthday": "Account",
      "createdAt": "2024-03-15T17:33:03.811Z",
      "updatedAt": "2024-03-16T02:36:16.796Z",
      "ids": "83"
    },
    {
      "username": "Vladimir",
      "password": "ggtQjbTYTqzHnOx",
      "email": "Rhea40@hotmail.com",
      "nickname": "Integration",
      "gender": "female",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "5",
      "isActive": "8",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#9b49fc",
      "address": "attitude",
      "story": "Hybrid",
      "workAt": "female",
      "studyAt": "Meadow",
      "favorites": "visionary",
      "birthday": "hertz",
      "createdAt": "2024-03-15T22:12:43.493Z",
      "updatedAt": "2024-03-15T14:13:16.534Z",
      "ids": "84"
    },
    {
      "username": "Camren",
      "password": "M_Gk0N9exJu0hlX",
      "email": "Alva2@gmail.com",
      "nickname": "Applications",
      "gender": "female",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "7",
      "isActive": "7",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#fcfdae",
      "address": "Caesium",
      "story": "aha",
      "workAt": "didactic",
      "studyAt": "Chromium",
      "favorites": "Bugatti",
      "birthday": "Account",
      "createdAt": "2024-03-15T17:33:57.326Z",
      "updatedAt": "2024-03-15T18:58:41.131Z",
      "ids": "85"
    },
    {
      "username": "Ruben",
      "password": "nhYXZnDHWlry8qE",
      "email": "Kristofer_Feest@yahoo.com",
      "nickname": "Southeast",
      "gender": "female",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "6",
      "isActive": "9",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#8f81c0",
      "address": "Evanston",
      "story": "second",
      "workAt": "Home",
      "studyAt": "Personal",
      "favorites": "transition",
      "birthday": "Usability",
      "createdAt": "2024-03-16T06:57:26.051Z",
      "updatedAt": "2024-03-15T14:52:59.197Z",
      "ids": "86"
    },
    {
      "username": "Arnaldo",
      "password": "SyDg119KaSqkPau",
      "email": "Kade_Doyle@hotmail.com",
      "nickname": "North",
      "gender": "female",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "5",
      "isActive": "7",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#b7f0b9",
      "address": "global",
      "story": "Connecticut",
      "workAt": "Chrysler",
      "studyAt": "Electronic",
      "favorites": "because",
      "birthday": "hacking",
      "createdAt": "2024-03-16T02:08:15.822Z",
      "updatedAt": "2024-03-16T08:42:06.557Z",
      "ids": "87"
    },
    {
      "username": "Rodrigo",
      "password": "WFcxlQOSf21B4bd",
      "email": "Pedro.Ebert26@yahoo.com",
      "nickname": "Tuna",
      "gender": "female",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "1",
      "isActive": "3",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#e6fcd2",
      "address": "utilize",
      "story": "Producer",
      "workAt": "Hop",
      "studyAt": "lavender",
      "favorites": "East",
      "birthday": "bellow",
      "createdAt": "2024-03-15T13:19:02.739Z",
      "updatedAt": "2024-03-15T21:15:48.256Z",
      "ids": "88"
    },
    {
      "username": "Libbie",
      "password": "G_2GNKOH79WxYig",
      "email": "Aglae.Nader88@yahoo.com",
      "nickname": "North",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "4",
      "isActive": "6",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#b90ecc",
      "address": "Iron",
      "story": "ducimus",
      "workAt": "monitor",
      "studyAt": "Gasoline",
      "favorites": "yahoo",
      "birthday": "quantify",
      "createdAt": "2024-03-15T22:24:00.009Z",
      "updatedAt": "2024-03-15T17:23:51.988Z",
      "ids": "89"
    },
    {
      "username": "Arthur",
      "password": "MbZSN9TSuPfWFC8",
      "email": "Sherman_Schinner@hotmail.com",
      "nickname": "SUV",
      "gender": "female",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "6",
      "isActive": "3",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#b1b0da",
      "address": "yellow",
      "story": "yellow",
      "workAt": "JSON",
      "studyAt": "intranet",
      "favorites": "Vineland",
      "birthday": "Southeast",
      "createdAt": "2024-03-16T07:28:29.889Z",
      "updatedAt": "2024-03-15T12:31:13.600Z",
      "ids": "90"
    },
    {
      "username": "Phyllis",
      "password": "q2Kspj26wROcciB",
      "email": "Emma_Maggio@hotmail.com",
      "nickname": "suscipit",
      "gender": "female",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "1",
      "isActive": "4",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#2efbf4",
      "address": "Strategist",
      "story": "than",
      "workAt": "West",
      "studyAt": "networks",
      "favorites": "Non",
      "birthday": "and",
      "createdAt": "2024-03-15T22:28:19.834Z",
      "updatedAt": "2024-03-15T16:51:49.000Z",
      "ids": "91"
    },
    {
      "username": "Lucio",
      "password": "L_6czyOPGvv7tL_",
      "email": "Hassan_Hauck@yahoo.com",
      "nickname": "Regional",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "8",
      "isActive": "5",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#cdccca",
      "address": "Electric",
      "story": "transmit",
      "workAt": "Metrics",
      "studyAt": "Hawaii",
      "favorites": "Michigan",
      "birthday": "rich",
      "createdAt": "2024-03-16T09:52:22.916Z",
      "updatedAt": "2024-03-15T18:49:54.680Z",
      "ids": "92"
    },
    {
      "username": "Korey",
      "password": "ZsAx3ymBdRcCoBs",
      "email": "Daisha_Stiedemann@gmail.com",
      "nickname": "Cheese",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "8",
      "isActive": "2",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#6ff54b",
      "address": "Southeast",
      "story": "slob",
      "workAt": "torment",
      "studyAt": "Chief",
      "favorites": "lightly",
      "birthday": "mint",
      "createdAt": "2024-03-16T04:47:04.651Z",
      "updatedAt": "2024-03-16T04:12:44.792Z",
      "ids": "93"
    },
    {
      "username": "Devan",
      "password": "SzLnFkVQdNkPeic",
      "email": "Jordyn35@yahoo.com",
      "nickname": "huzzah",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "1",
      "isActive": "1",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#388cac",
      "address": "pink",
      "story": "distributed",
      "workAt": "Berkshire",
      "studyAt": "Tanzania",
      "favorites": "red",
      "birthday": "Kong",
      "createdAt": "2024-03-15T21:49:38.338Z",
      "updatedAt": "2024-03-15T16:03:41.062Z",
      "ids": "94"
    },
    {
      "username": "Bernhard",
      "password": "fFgbZiNeZdJUJ1S",
      "email": "Cathryn3@yahoo.com",
      "nickname": "indeed",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "1",
      "isActive": "2",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#4d4cdd",
      "address": "green",
      "story": "Southeast",
      "workAt": "SUV",
      "studyAt": "interfaces",
      "favorites": "Northwest",
      "birthday": "radian",
      "createdAt": "2024-03-16T02:14:49.740Z",
      "updatedAt": "2024-03-16T00:19:32.850Z",
      "ids": "95"
    },
    {
      "username": "Vladimir",
      "password": "hDTwLHVwg20DPd3",
      "email": "Zechariah62@yahoo.com",
      "nickname": "Cambridgeshire",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "4",
      "isActive": "2",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#3146a5",
      "address": "tertiary",
      "story": "Minivan",
      "workAt": "Homestead",
      "studyAt": "nulla",
      "favorites": "ivory",
      "birthday": "AGP",
      "createdAt": "2024-03-15T23:33:59.686Z",
      "updatedAt": "2024-03-16T05:15:08.085Z",
      "ids": "96"
    },
    {
      "username": "Elwin",
      "password": "6GTgp6dLNxZvvgd",
      "email": "Riley26@yahoo.com",
      "nickname": "Pennsylvania",
      "gender": "female",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "1",
      "isActive": "8",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#ffa0bf",
      "address": "useful",
      "story": "Zulauf",
      "workAt": "Schinner",
      "studyAt": "partnerships",
      "favorites": "disassemble",
      "birthday": "Principal",
      "createdAt": "2024-03-16T01:13:10.755Z",
      "updatedAt": "2024-03-15T22:19:37.710Z",
      "ids": "97"
    },
    {
      "username": "Urban",
      "password": "XGN84zHvdkznXdN",
      "email": "Clarissa_Kuphal99@yahoo.com",
      "nickname": "programming",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "3",
      "isActive": "1",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#efc59d",
      "address": "calculating",
      "story": "ugh",
      "workAt": "payment",
      "studyAt": "male",
      "favorites": "Northeast",
      "birthday": "Aluminium",
      "createdAt": "2024-03-15T20:44:23.341Z",
      "updatedAt": "2024-03-16T11:07:36.085Z",
      "ids": "98"
    },
    {
      "username": "Joannie",
      "password": "xJUWYZwfnZvmFOG",
      "email": "Adam.Jaskolski25@yahoo.com",
      "nickname": "dreamily",
      "gender": "male",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "6",
      "isActive": "2",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#19b499",
      "address": "quantifying",
      "story": "West",
      "workAt": "Refined",
      "studyAt": "despite",
      "favorites": "Account",
      "birthday": "algorithm",
      "createdAt": "2024-03-16T01:33:00.435Z",
      "updatedAt": "2024-03-15T22:06:06.671Z",
      "ids": "99"
    },
    {
      "username": "Oliver",
      "password": "pfd4WxvxY8RjQ_l",
      "email": "Elwyn82@gmail.com",
      "nickname": "Virginia",
      "gender": "female",
      "avatar": "https://loremflickr.com/640/480/food",
      "smallAvatar": "https://loremflickr.com/640/480/food",
      "confirm": "3",
      "isActive": "5",
      "background": "https://loremflickr.com/640/480/food",
      "backgroundColor": "#9b5ed1",
      "address": "Data",
      "story": "Northwest",
      "workAt": "Handmade",
      "studyAt": "violet",
      "favorites": "Forward",
      "birthday": "Soft",
      "createdAt": "2024-03-16T03:06:48.863Z",
      "updatedAt": "2024-03-16T11:19:37.826Z",
      "ids": "100"
    }
  ])
  res.status(200).json("Ngon")
});

module.exports = router;